# Generated by Django 6.0 on 2025-12-30 01:51

import main.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='prompt',
            field=main.fields.EncryptedTextField(help_text='Encrypted user prompt'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='response',
            field=main.fields.EncryptedTextField(help_text='Encrypted AI response'),
        ),
    ]
