# Generated by Django 6.0 on 2025-12-30 03:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def create_default_session_and_assign_conversations(apps, schema_editor):
    """Create a default session and assign all existing conversations to it"""
    ChatSession = apps.get_model('chat', 'ChatSession')
    Conversation = apps.get_model('chat', 'Conversation')
    
    # Create a default session for existing conversations
    default_session = ChatSession.objects.create(
        id=uuid.uuid4(),
        title='Previous Conversations',
        created_at=django.utils.timezone.now(),
        updated_at=django.utils.timezone.now()
    )
    
    # Assign all existing conversations to the default session
    Conversation.objects.all().update(session=default_session)


def reverse_migration(apps, schema_editor):
    """Reverse migration - nothing to do"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_conversation_prompt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['created_at'], 'verbose_name': 'Conversation', 'verbose_name_plural': 'Conversations'},
        ),
        migrations.AddField(
            model_name='conversation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='Auto-generated from first message', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Session',
                'verbose_name_plural': 'Chat Sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='chat.chatsession'),
        ),
        migrations.RunPython(create_default_session_and_assign_conversations, reverse_migration),
        migrations.AlterField(
            model_name='conversation',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='chat.chatsession'),
        ),
    ]
