# Generated by Django 5.1.4 on 2024-12-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_appointment_appointment_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
