# Generated by Django 5.1.4 on 2025-01-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='medical_history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
