# Generated by Django 6.0 on 2025-12-30 01:51

import django.db.models.deletion
import main.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_appointment_medical_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='medical_history',
            field=main.fields.EncryptedTextField(blank=True, help_text='Encrypted medical history for appointment', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=main.fields.EncryptedTextField(blank=True, help_text='Encrypted appointment notes', null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=main.fields.EncryptedTextField(help_text='Encrypted contact message'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='phone_number',
            field=main.fields.EncryptedCharField(blank=True, help_text='Encrypted phone number', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='contact_number',
            field=main.fields.EncryptedCharField(blank=True, help_text='Encrypted contact number', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='medical_history',
            field=main.fields.EncryptedTextField(blank=True, help_text='Encrypted medical history'),
        ),
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(help_text='Encrypted file storage', upload_to='patient_reports/'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'View'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('export', 'Export'), ('access', 'Access')], max_length=20)),
                ('resource_type', models.CharField(choices=[('patient_profile', 'Patient Profile'), ('appointment', 'Appointment'), ('medical_history', 'Medical History'), ('report', 'Medical Report'), ('scan', 'Medical Scan'), ('conversation', 'Chat Conversation')], max_length=50)),
                ('resource_id', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log Entry',
                'verbose_name_plural': 'Audit Log Entries',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='main_auditl_user_id_1cd3b6_idx'), models.Index(fields=['resource_type', 'resource_id'], name='main_auditl_resourc_d9bb78_idx'), models.Index(fields=['action', 'timestamp'], name='main_auditl_action_61f1e6_idx')],
            },
        ),
    ]
