# Generated by Django 6.0 on 2025-12-30 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scan',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Medical Scan', 'verbose_name_plural': 'Medical Scans'},
        ),
        migrations.AddField(
            model_name='scan',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scan',
            name='scan_type',
            field=models.CharField(choices=[('CKD', 'Chronic Kidney Disease (CKD)'), ('XRAY', 'X-Ray'), ('MRI', 'Magnetic Resonance Imaging (MRI)'), ('CT', 'Computed Tomography (CT Scan)'), ('ULTRASOUND', 'Ultrasound'), ('MAMMOGRAPHY', 'Mammography'), ('ECG', 'Electrocardiogram (ECG)'), ('OTHER', 'Other')], default='CKD', help_text='Select the type of medical scan', max_length=20),
        ),
    ]
